# Generated by Django 2.1 on 2023-05-14 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congestion', models.IntegerField()),
                ('car_congestion', models.CharField(max_length=100)),
                ('info_delivery_deadline', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'congestion',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='SubwayLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'subway_line',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.Station')),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='subway_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.SubwayLine'),
        ),
        migrations.AddField(
            model_name='congestion',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.Train'),
        ),
        migrations.AddIndex(
            model_name='train',
            index=models.Index(fields=['status', 'direction', 'station'], name='train_status_d65ba4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='train',
            unique_together={('number', 'status', 'direction')},
        ),
    ]
