# Generated by Django 2.1 on 2023-05-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='train',
            name='train_status_d65ba4_idx',
        ),
        migrations.AddIndex(
            model_name='train',
            index=models.Index(fields=['status', 'direction', 'station'], name='pica_train_status_e5a5d1_idx'),
        ),
        migrations.AlterModelTable(
            name='congestion',
            table='pica_congestion',
        ),
        migrations.AlterModelTable(
            name='station',
            table='pica_station',
        ),
        migrations.AlterModelTable(
            name='subwayline',
            table='pica_subway_line',
        ),
        migrations.AlterModelTable(
            name='train',
            table='pica_train',
        ),
    ]
