# Generated by Django 2.1 on 2023-05-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0002_auto_20230506_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwayline',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subwayline',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subwayname',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subwayname',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='traincongestion',
            name='subway_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_manage.SubwayName'),
        ),
        migrations.AlterField(
            model_name='traincongestion',
            name='train_congestion',
            field=models.IntegerField(),
        ),
    ]
