# Generated by Django 2.1 on 2023-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0003_auto_20230511_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traincongestion',
            name='train_car_congestion',
            field=models.CharField(max_length=100),
        ),
    ]
