# Generated by Django 2.1 on 2023-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0004_auto_20230511_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traincongestion',
            name='train_info_delivery_deadline',
            field=models.CharField(max_length=50),
        ),
    ]
