# Generated by Django 2.1 on 2023-05-15 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0005_auto_20230515_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congestion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 17, 15, 5)),
        ),
        migrations.AlterField(
            model_name='congestion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 17, 15, 5)),
        ),
        migrations.AlterField(
            model_name='train',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 17, 15, 5)),
        ),
        migrations.AlterField(
            model_name='train',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 17, 15, 5)),
        ),
    ]
