# Generated by Django 2.1 on 2023-05-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0005_auto_20230511_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traincongestion',
            name='subway_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.SubwayName'),
        ),
    ]
