# Generated by Django 2.1 on 2023-05-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0006_auto_20230513_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwayline',
            name='subway_line',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subwayname',
            name='subway_name',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='traincongestion',
            index=models.Index(fields=['train_status', 'train_up_down', 'subway_name'], name='pica_train__train_s_1eb2a6_idx'),
        ),
    ]
