# Generated by Django 2.1 on 2023-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0008_auto_20230515_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congestion',
            name='info_delivery_deadline',
            field=models.DateTimeField(),
        ),
    ]
