# Generated by Django 2.1 on 2023-05-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0008_auto_20230515_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('video_url', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.Station')),
                ('subway_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.SubwayLine')),
            ],
            options={
                'db_table': 'pica_cctv',
            },
        ),
        migrations.CreateModel(
            name='DetectedCCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('video_url', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cctv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_manage.CCTV')),
            ],
            options={
                'db_table': 'pica_detected_cctv',
            },
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.CharField(max_length=100)),
                ('line_start', models.CharField(max_length=50)),
                ('line_end', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('cctv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_manage.CCTV')),
            ],
            options={
                'db_table': 'pica_polygon',
            },
        ),
        migrations.AlterField(
            model_name='congestion',
            name='congestion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='congestion',
            name='info_delivery_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='detectedcctv',
            index=models.Index(fields=['name', 'video_url'], name='pica_detect_name_bcec67_idx'),
        ),
        migrations.AddIndex(
            model_name='cctv',
            index=models.Index(fields=['name', 'video_url'], name='pica_cctv_name_eff0bb_idx'),
        ),
    ]
