# Generated by Django 2.1 on 2023-05-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0009_auto_20230519_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_train', models.IntegerField()),
                ('out_train', models.IntegerField()),
                ('max_count', models.IntegerField()),
                ('density', models.FloatField()),
                ('density_degree', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('detected_cctv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_manage.DetectedCCTV')),
            ],
            options={
                'db_table': 'pica_headcount',
            },
        ),
        migrations.AddIndex(
            model_name='headcount',
            index=models.Index(fields=['density_degree', 'detected_cctv'], name='pica_headco_density_567ef2_idx'),
        ),
    ]
