# Generated by Django 2.1 on 2023-05-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0009_auto_20230516_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedCCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pica_detected_cctv',
            },
        ),
        migrations.CreateModel(
            name='OriginalCCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.Station')),
                ('subway_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_manage.SubwayLine')),
            ],
            options={
                'db_table': 'pica_original_cctv',
            },
        ),
        migrations.AddField(
            model_name='detectedcctv',
            name='original_cctv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_manage.OriginalCCTV'),
        ),
    ]
