# Generated by Django 2.1 on 2023-05-18 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0010_detectedcctv_originalcctv'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcctv',
            name='original_cctv',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='train_manage.OriginalCCTV'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectedcctv',
            name='video_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='originalcctv',
            name='video_url',
            field=models.CharField(max_length=255),
        ),
    ]
