# Generated by Django 2.1 on 2023-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0010_auto_20230518_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='congestion',
            name='no1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congestion',
            name='no9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='congestion',
            name='congestion',
            field=models.IntegerField(default=0),
        ),
    ]
