# Generated by Django 2.1 on 2023-05-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0011_auto_20230518_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congestion',
            name='car_congestion',
        ),
    ]
