# Generated by Django 2.1 on 2023-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_manage', '0011_auto_20230518_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedcctv',
            name='video_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='originalcctv',
            name='video_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
